name: Basic CI - Compilation Check

on: [push, pull_request]

jobs:
  build-firmware:
    name: Build Firmware
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: firmware

    steps:
    - name: Checkout code + submodules
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 1 
      
    - name: Install & Cache ARM Toolchain
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi
        version: 1.0

    - name: Verify toolchain
      run: |
        arm-none-eabi-gcc --version
        arm-none-eabi-ld --version
        find /usr -name "libc.a" 2>/dev/null | grep arm-none-eabi

    - name: Compile Project
      run: make all