name: Basic CI - Compilation Check

on: [push, pull_request]

jobs:
  build-firmware:
    name: Build Firmware
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: firmware

    steps:
    - name: Checkout code + submodules
      uses: actions/checkout@v4
      with:
        submodules: 'recursive' 

    - name: Install ARM GCC Toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi

    - name: Compile Project
      run: make all
