name: Basic CI - Compilation Check

on: [push, pull_request]
env:
  CACHE_KEY: toolchain-arm-gcc-1

jobs:
  build-firmware:
    name: Build Firmware
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: firmware

    steps:
    - name: Checkout code + submodules
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 1 

    - name: Cache ARM GCC Toolchain
      uses: actions/cache@v3
      id: cache-toolchain
      with:
        path: /usr/bin/arm-none-eabi-*
        key: ${{ runner.os }}-${{ env.CACHE_KEY }}

    - name: Install ARM GCC Toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi



    - name: Verify toolchain
      run: |
        arm-none-eabi-gcc --version
        which arm-none-eabi-gcc

    - name: Compile Project
      run: make all
